default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  passowrd:

development:
  <<: *default
  host: db
  database: pomodoro_development

test:
  <<: *default
  host: db
  database: pomodoro_test

production:
  <<: *default
  database: pomodoro_production
  username: pomodoro
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>